### ISSUE TITLE
TypeError: Cannot read property 'kind' of undefined at isAngularDecoratorMetadataExpression

### ISSUE THREAD

**Issue by agap2-ag** [mdbootstrap/perfect-scrollbar#932]
- [X] Check [FAQ](https://github.com/mdbootstrap/perfect-scrollbar/wiki/FAQ) and [Caveats](https://github.com/mdbootstrap/perfect-scrollbar/wiki/Caveats)
- [X] Search if there's already one reported in Issues
- [ ] Prepare a JSFiddle reproducing the issue
  - [perfect-scrollbar JSFiddle](https://jsfiddle.net/utatti/dyvL31r6/)
- [ ] Provide a page or source code where the issue can be checked

While building (similar to another TypeError issue: #762):

> **ERROR in ./node_modules/ngx-perfect-scrollbar/fesm5/ngx-perfect-scrollbar.js**
> Module build failed (from ./node_modules/@angular-devkit/build-optimizer/src/build-optimizer/webpack-loader.js):
> TypeError: **Cannot read property 'kind' of undefined**
>     at isAngularDecoratorMetadataExpression (/Users/tlavant/builds/11902ea7/0/sqool/sqool_electron_session/student/node_modules/@angular-devkit/build-optimizer/src/transforms/scrub-file.js:230:35)
>     at checkNodeForDecorators (/Users/tlavant/builds/11902ea7/0/sqool/sqool_electron_session/student/node_modules/@angular-devkit/build-optimizer/src/transforms/scrub-file.js:53:21)
>     at visitNodes (/Users/tlavant/builds/11902ea7/0/sqool/sqool_electron_session/student/node_modules/typescript/lib/typescript.js:16631:30)
>     at Object.forEachChild (/Users/tlavant/builds/11902ea7/0/sqool/sqool_electron_session/student/node_modules/typescript/lib/typescript.js:16857:24)
>     at checkNodeForDecorators (/Users/tlavant/builds/11902ea7/0/sqool/sqool_electron_session/student/node_modules/@angular-devkit/build-optimizer/src/transforms/scrub-file.js:44:31)
>     at visitNode (/Users/tlavant/builds/11902ea7/0/sqool/sqool_electron_session/student/node_modules/typescript/lib/typescript.js:16622:24)
>     at Object.forEachChild (/Users/tlavant/builds/11902ea7/0/sqool/sqool_electron_session/student/node_modules/typescript/lib/typescript.js:16752:21)
>     at checkNodeForDecorators (/Users/tlavant/builds/11902ea7/0/sqool/sqool_electron_session/student/node_modules/@angular-devkit/build-optimizer/src/transforms/scrub-file.js:44:31)
>     at visitNode (/Users/tlavant/builds/11902ea7/0/sqool/sqool_electron_session/student/node_modules/typescript/lib/typescript.js:16622:24)
>     at Object.forEachChild (/Users/tlavant/builds/11902ea7/0/sqool/sqool_electron_session/student/node_modules/typescript/lib/typescript.js:16809:24)
>     at checkNodeForDecorators (/Users/tlavant/builds/11902ea7/0/sqool/sqool_electron_session/student/node_modules/@angular-devkit/build-optimizer/src/transforms/scrub-file.js:44:31)
>     at visitNode (/Users/tlavant/builds/11902ea7/0/sqool/sqool_electron_session/student/node_modules/typescript/lib/typescript.js:16622:24)
>     at Object.forEachChild (/Users/tlavant/builds/11902ea7/0/sqool/sqool_electron_session/student/node_modules/typescript/lib/typescript.js:16820:24)
>     at checkNodeForDecorators (/Users/tlavant/builds/11902ea7/0/sqool/sqool_electron_session/student/node_modules/@angular-devkit/build-optimizer/src/transforms/scrub-file.js:44:31)
>     at visitNode (/Users/tlavant/builds/11902ea7/0/sqool/sqool_electron_session/student/node_modules/typescript/lib/typescript.js:16622:24)
>     at Object.forEachChild (/Users/tlavant/builds/11902ea7/0/sqool/sqool_electron_session/student/node_modules/typescript/lib/typescript.js:16716:21)
> error Command failed with exit code 1.

**Comment by DenisSemionov** [comment]
But this is not related to this repo. You need to create an issue here:

https://github.com/zefoy/ngx-perfect-scrollbar

**Comment by agap2-ag** [comment]
> 
> 
> But this is not related to this repo. You need to create an issue here:
> 
> https://github.com/zefoy/ngx-perfect-scrollbar

Indeed the plugin I am using is the _ngx-perfect-scrollbar_ and there's already an issue opened about this in the ngx plugin (which is just an Angular wrapper of MDB's perfect scrollbar).

However, since there are older similar issues opened here (#762), I was wondering if the solution could be applicable to all.
